In [5]:
# pip install mysql-connector-python

In [9]:
import mysql.connector # Connect to the MySQL database
conn = mysql.connector.connect(
    user='root',   
    password='',   
    host='localhost'
)
# Create a cursor object 
cursor = conn.cursor() # Create a new database
query = "CREATE DATABASE bimp"
cursor.execute(query)# Use the new database
query = "USE bimp" 
cursor.execute(query)# Create a new table
query = """
    CREATE TABLE users (
        id INT AUTO_INCREMENT,
        name VARCHAR(255),
        address VARCHAR(255),
        PRIMARY KEY (id)
    )
"""
cursor.execute(query)# Commit the changes
conn.commit()# Close the cursor and connection
cursor.close() 
conn.close()

DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)

In [ ]:
import mysql.connector

# Connect to the MySQL database
cnx = mysql.connector.connect(
    user='root',
    password='password',
    host='localhost'
)

# Create a cursor object
cursor = cnx.cursor()

# Use the new database
query = "USE bimp"
cursor.execute(query)

# Insert a new record
query = "INSERT INTO users (name, address) VALUES (%s, %s)"
values = ('Ram', 'Biratnagar')
cursor.execute(query, values)

# values = [('Shyam', 'Dharan'),('Hari', 'Itahari')]
# cursor.executemany(query, values)

# Commit the changes
cnx.commit()

# Close the cursor and connection
cursor.close()
cnx.close()

In [ ]:
import mysql.connector

# Connect to the MySQL database
cnx = mysql.connector.connect(
    user='root',
    password='password',
    host='localhost'
)

# Create a cursor object
cursor = cnx.cursor()

# Use the new database
query = "USE bimp"
cursor.execute(query)

# Create a cursor object
cursor = cnx.cursor()

# Retrieve all records from the table
query = "SELECT * FROM users"
cursor.execute(query)

# Fetch all the rows
rows = cursor.fetchall()

# Print the results
for row in rows:
    print(row)

# Close the cursor and connection
cursor.close()
cnx.close()

In [ ]:
import mysql.connector

# Connect to the MySQL database
cnx = mysql.connector.connect(
    user='root',
    password='password',
    host='localhost',
    database='bimp'
)

# Create a cursor object
cursor = cnx.cursor()

# Update a record
query = "UPDATE users SET name = %s, address = %s WHERE id = %s"
values = ('Shyam', 'Dharan', 1)
cursor.execute(query, values)

# Commit the changes
cnx.commit()

# Close the cursor and connection
cursor.close()
cnx.close()

In [ ]:
# Connect to the MySQL database
cnx = mysql.connector.connect(
    user='root',
    password='password',
    host='localhost',
    database='bimp'
)

# Create a cursor object
cursor = cnx.cursor()

# # Delete a record
# query = "DELETE FROM users WHERE id = %s"
# values = [1]
# cursor.execute(query, values)

# # Delete multiple records
# query = "DELETE FROM users WHERE id IN (%s, %s)"
# values = (2, 3)
# cursor.execute(query, values)

# Delete multiple records
query = "DELETE FROM users WHERE id = %s"
values = [(4,),]
cursor.executemany(query, values)

# Commit the changes
cnx.commit()

# Close the cursor and connection
cursor.close()
cnx.close()